# 股票池选股配置文件

# API配置
tushare_token: "eaf33a386c2131d066dce3c7b777d519fdd054d59dd2a5f038d4623b"

# 股票池代码列表
stock_code: 
  - '002594.SZ'  # 比亚迪
  - '600750.SH'  # 恒生电子
  - '601127.SH'  # 赛力斯
  - '601888.SH'  # 中国中免
  - '300750.SZ'  # 宁德时代
  - '600036.SH'  # 招商银行
  - '600519.SH'  # 贵州茅台
  - '688981.SH'  # 中芯国际
  - '688041.SH'  # 海光信息

# 数据配置
update_data: True  # 是否更新本地数据库中的数据
start_date: '20130101'  # 数据开始日期
end_date: ''  # 数据结束日期，留空表示当前日期

# 回测配置
backtest:
  start_capital: 100000  # 初始资金：10万元
  commission_rate: 0.001  # 交易成本：千分之1
  slippage: 0.0005  # 滑点：0.05%
  start_date: ''  # 回测开始日期，默认会设置为距今一年
  end_date: ''  # 回测结束日期，默认为最新日期

# KDJ指标参数
kdj:
  n: 9  # KDJ的N参数
  m1: 3  # KDJ的M1参数
  m2: 3  # KDJ的M2参数
  buy_threshold: 0  # 买入信号：J值低于该值
  sell_threshold: 70  # 卖出信号：J值高于该值 